name: Cancel (Devel)
on:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: android-ci.yml, emscripten.yml, continuous_integration.yml, macos-ci.yml, vita.yml
          all_but_latest: true
          access_token: ${{ github.token }}
